# Generated by Django 5.0.6 on 2024-06-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='overview',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='starting_price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
