# Generated by Django 5.0.6 on 2024-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_image_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FASHION', 'Fashion'), ('ELECTRONICS', 'Electronics'), ('TOYS', 'Toys'), ('HOME', 'Home'), ('FOOD', 'Food'), ('BEVERAGES', 'Beverages'), ('BEAUTY', 'Beauty and Personal Products')], default=None, max_length=11, null=True),
        ),
    ]
