# Generated by Django 5.0.6 on 2024-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist_listings',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to='auctions.listing'),
        ),
    ]
