# Generated by Django 5.0.6 on 2024-06-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_user_watchlist_user_watchlist_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist_listings',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to='auctions.listing'),
        ),
    ]
