# Generated by Django 5.0.6 on 2024-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_bid_alter_listing_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.CharField(max_length=20),
        ),
    ]
