# Generated by Django 5.0.6 on 2024-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='bid_listing', to='auctions.bid'),
        ),
    ]
