# Generated by Django 5.0.6 on 2024-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
